/github/workspace/test/unit/mode.F90 File Reference
Tests for the mam_mode module.
Functions/Subroutines
real(kind=dk) function, dimension(2) asymmetry_factor (mode, mode_state, long_or_short)
complex(kind=dk) function, dimension(2) net_refractive_index (mode_state, long_or_short)
real(kind=dk) function, dimension(2) specific_absorption (mode, mode_state, long_or_short)
real(kind=dk) function, dimension(2) specific_extinction (mode, mode_state, long_or_short)
program test_mode
Test program for the mode_t type and related functions.
subroutine test_mode_t ()
Detailed Description
Tests for the mam_mode module.
Function/Subroutine Documentation
asymmetry_factor()
real(kind=dk) function, dimension(2) test_mode::asymmetry_factor (class(mode_t), intent(in) mode, class(mode_state_t), intent(in) mode_state, integer, intent(in) long_or_short)
Definition at line 533 of file mode.F90.
net_refractive_index()
complex(kind=dk) function, dimension(2) test_mode::net_refractive_index (class(mode_state_t), intent(in) mode_state, integer, intent(in) long_or_short)
Definition at line 328 of file mode.F90.
Referenced by test_mode_t().
specific_absorption()
real(kind=dk) function, dimension(2) test_mode::specific_absorption (class(mode_t), intent(in) mode, class(mode_state_t), intent(in) mode_state, integer, intent(in) long_or_short)
Definition at line 372 of file mode.F90.
Referenced by test_mode_t().
specific_extinction()
real(kind=dk) function, dimension(2) test_mode::specific_extinction (class(mode_t), intent(in) mode, class(mode_state_t), intent(in) mode_state, integer, intent(in) long_or_short)
Definition at line 454 of file mode.F90.
Referenced by test_mode_t().
test_mode()
program test_mode
Test program for the mode_t type and related functions.
Definition at line 8 of file mode.F90.
test_mode_t()
subroutine test_mode::test_mode_t
Definition at line 18 of file mode.F90.
Referenced by test_mode().