name: Test CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t mam-test .
    - name: run tests in container
      run: docker run -it mam-test bash -c 'cd /build; make test'
